# Generated by Django 4.1 on 2022-11-07 20:51

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=user.models.get_default_profile_image, null=True, upload_to=user.models.get_profile_image_filepath),
        ),
    ]
