# Generated by Django 4.1 on 2022-11-20 12:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=user.models.get_default_profile_image, null=True, upload_to=user.models.get_profile_image_filepath),
        ),
    ]
