# Generated by Django 4.1 on 2022-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='video-cover'),
        ),
        migrations.AddField(
            model_name='video',
            name='speciality',
            field=models.CharField(choices=[('Neuerscheinungen', 'Neuerscheinungen'), ('Serien', 'Serien'), ('Filme', 'Filme')], default='Filme', max_length=20),
        ),
    ]
